---
title: "IMA_first_Project"
authors: The Knights
output: html_document
---

```{r}
LIBOR <- read.csv("LIBOR_USD.csv")
```

```{r warning=FALSE}
library(lubridate)
library(dplyr)
library(ggplot2)
library(plotly)
library(timeDate)
library(car)
library(lme4)
```

## Finding The right rate to track

```{r}
### this is a funciton that converts the interest rate data to data on percent change of interest rate
add_percent_change_libor <- function(data){
  new_data = cbind(data[-1, ], data.frame(Percent_Change_ON = 100 * diff(log(data$ON)), Percent_Change_1W = 100 * diff(log(data$X1W)), Percent_Change_1M = 100 * diff(log(data$X1M)), Percent_Change_2M = 100 * diff(log(data$X2M)), Percent_Change_3M = 100 * diff(log(data$X3M)), Percent_Change_6M = 100 * diff(log(data$X6M)), Percent_Change_12M = 100 * diff(log(data$X12M))))
  return(new_data)
}

LIBOR_pc <- add_percent_change_libor(LIBOR) ## convert the data to percent change 
```

```{r}
##############################################################################
# Create a new table with column name "time stamp" containing entries with format Year-Month-Day 
##############################################################################
days_before_holiday <- 10
days_after_holiday <- 10
rates_to_track <- LIBOR_pc

# Convert date format to year-month-day
rates_to_track <- rates_to_track  %>% mutate(timestamp = as.Date(dmy(rates_to_track$Date)))  
##############################################################################

```

```{r}
##############################################################################

# listHolidays() will give you a list of possible holidays to use
# In this case, we're using ChristmasDay

holiday_var = "ChristmasDay"
holidays <- c(holiday_var)  
Year_begin = 2003
Year_end = 2019

#https://stackoverflow.com/questions/41825688/loop-over-holidays-in-timedate-package

# Create a Table named "holiday_dates" line 59-63
  
# Holiday        | Date 
# ChristmasDay     2003-12-25
# ChristmasDay     2004-12-25
# ............     ..........
# ChristmasDay     2009-12-25 

holiday_dates = do.call(rbind,
        lapply(holidays, function(i){
          foo <- match.fun(i)  
          data.frame(Holiday = i,
                     Date = as.Date(foo(Year_begin:Year_end)))
        }))
#############################################################################
```

```{r}
## a function that finds how far a date is from the given holiday (the minimum distance). returns a column of this distance and the year of the holiday

close_to_holiday <- function(input_date){
  distance_from_all_holidays <- mutate(holiday_dates, relative_date = floor(as.period(interval(Date, input_date) ) %/% days(1) ) )%>%
    mutate(absolute_relative_date = abs(relative_date)) %>% arrange(absolute_relative_date)
  return(c(distance_from_all_holidays[1, "relative_date"], year(distance_from_all_holidays[1, "Date"])))
}

#############################################################################

```

```{r}

# next two functions are a hack to make the dataframe wrangling work, can be made better 
get_relative_date <- function(input_date){
  return(close_to_holiday(input_date)[1])
}

get_relative_holiday_year <- function(input_date){
  return(close_to_holiday(input_date)[2])
}

#############################################################################

####### Finally, add relative holiday data to the dataframe and filter for the days you need 

rates_to_track_with_holiday_data <- rates_to_track %>% mutate(relative_date = sapply(timestamp, get_relative_date) ) %>% mutate(holiday_year = sapply(timestamp, get_relative_holiday_year)) %>%
  dplyr::filter(relative_date >= days_before_holiday * -1 & relative_date <= days_after_holiday)

write.csv(rates_to_track_with_holiday_data, "filtered_data.csv")

```


```{r}
## Add before and after holiday, function 
before_after <- function(dataframe){
  dataframe <- mutate(dataframe, pre = ifelse(relative_date <= 0, TRUE, FALSE))
  return(dataframe)
}
```

```{r}
rates_to_track_with_holiday_data <- before_after(rates_to_track_with_holiday_data)
```



```{r}
View(rates_to_track_with_holiday_data)

```




```{r}
model1 <- lmer(ON ~ pre + (1|holiday_year), data = rates_to_track_with_holiday_data, REML = FALSE)
summary(model1)

```


```{r}
library(car)
Anova(model1)
```



```{r}
ggplot(rates_to_track_with_holiday_data, aes(x = relative_date, y = Percent_Change_ON, color = as.factor(holiday_year))) + geom_point()
```





























## Fiting Model by Xin
```{r}
####################
##add a column of percentage change 
LIBOR_PC = cbind(data.frame(Percent_Change_ON = 100 * diff(log(rates_to_track_with_holiday_data$ON)), Percent_Change_1W = 100 * diff(log(rates_to_track_with_holiday_data$X1W))), 
                 rates_to_track_with_holiday_data[-1, ])

Dec_Jan = LIBOR_PC %>%
  ##convert the Date into a timestamp class
  mutate(timestamp = dmy(LIBOR_PC$Date)) %>%
  mutate(Year = year(timestamp), MonthDay = format(timestamp, "%m%d")) %>%
  filter(MonthDay >= "1217" | MonthDay <= "0108") %>%
  mutate(Pre = ifelse(MonthDay > "1224", "Post", ifelse(MonthDay <= "0131", "Post", "Pre"))) 
  
############################################





###########################################


  
#write.csv(Dec_Jan, "Dec_Jan.csv")

One_Year = Dec_Jan %>%
  filter(between(timestamp, as.Date("2018-12-17"), as.Date("2019-01-08")))

ggplot(Dec_Jan, aes(y = ON, x = MonthDay, group = Year, color = Year)) + geom_point() + geom_line()

ggplot(One_Year, aes(y = ON, x = timestamp)) + geom_point() 

###percentage change
############problem 
##add a column of percentage change of overnight interest rate percentage change
#mutate(Percenate_Change = diff(log(ON)))

summary(lm(Percent_Change_ON ~  Pre , data = Dec_Jan))

summary(lm(Percent_Change_1W ~  Pre , data = Dec_Jan))

ggplot(Dec_Jan, aes(y = Percent_Change_1W, x = timestamp)) + geom_point() + geom_smooth(method = "lm")
ggplot(Dec_Jan, aes(y = Percent_Change_1W, x = timestamp, group = Pre, color = Pre)) + geom_point() + geom_smooth(method = "lm")




```


<!-- ##### You migh ignore the rest of my trial and error code for todays!!! -->


<!-- ```{r} -->
<!-- Dec_Jan = LIBOR %>% -->
<!--   ##convert the Date into a timestamp class -->
<!--   mutate(timestamp = dmy(LIBOR$Date)) %>% -->
<!--   mutate(Year = year(timestamp), MonthDay = format(timestamp, "%m%d")) %>% -->
<!--   filter(MonthDay >= "1217" | MonthDay <= "0108")  -->

<!-- view(Dec_Jan) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- DecJan_2018<-Dec_Jan %>% -->
<!-- filter(between(timestamp,as.Date("2018-12-17"), as.Date("2019-01-08")))   -->

<!-- view(DecJan_2018) -->



<!-- DecJan_2017<-Dec_Jan %>% -->
<!-- filter(between(timestamp,as.Date("2017-12-17"), as.Date("2018-01-08")))   -->


<!-- DecJan_2016<-Dec_Jan %>% -->
<!-- filter(between(timestamp,as.Date("2016-12-17"), as.Date("2017-01-08")))  -->



<!-- DecJan_2015<-Dec_Jan %>% -->
<!-- filter(between(timestamp,as.Date("2015-12-17"), as.Date("2016-01-08")))  -->


<!-- DecJan_2014<-Dec_Jan %>% -->
<!-- filter(between(timestamp,as.Date("2014-12-17"), as.Date("2015-01-08")))  -->

<!-- DecJan_2013<-Dec_Jan %>% -->
<!-- filter(between(timestamp,as.Date("2013-12-17"), as.Date("2014-01-08")))  -->


<!-- DecJan_2012<-Dec_Jan %>% -->
<!-- filter(between(timestamp,as.Date("2012-12-17"), as.Date("2013-01-08")))  -->

<!-- view(DecJan_2018) -->
<!-- ``` -->

<!-- ```{r} -->

<!-- ``` -->
<!-- ```{r} -->
<!-- p1 <- plot_ly(DecJan_2015, x = ~timestamp, y = ~ON) %>% -->
<!--   add_lines(name = ~"2015") -->
<!-- p2 <- plot_ly(DecJan_2016, x = ~timestamp, y = ~ON) %>% -->
<!--   add_lines(name = ~"2016") -->
<!-- p3 <- plot_ly(DecJan_2017, x = ~timestamp, y = ~ON) %>% -->
<!--   add_lines(name = ~"2017") -->
<!-- p4 <- plot_ly(DecJan_2018, x = ~timestamp, y = ~ON) %>% -->
<!--   add_lines(name = ~"2018") -->
<!-- p <- subplot(p1, p2,p3,p4) -->
<!-- ``` -->

<!-- ```{r} -->

<!-- p1 <- plot_ly(DecJan_2015, x = ~timestamp, y = ~X1W) %>% -->
<!--   add_lines(name = ~"2015") -->
<!-- p2 <- plot_ly(DecJan_2016, x = ~timestamp, y = ~X1W) %>% -->
<!--   add_lines(name = ~"2016") -->
<!-- p3 <- plot_ly(DecJan_2017, x = ~timestamp, y = ~X1W) %>% -->
<!--   add_lines(name = ~"2017") -->
<!-- p4 <- plot_ly(DecJan_2018, x = ~timestamp, y = ~X1W) %>% -->
<!--   add_lines(name = ~"2018") -->
<!-- p_1W <- subplot(p1, p2,p3,p4) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- # Add a scatterplot layer -->
<!-- ggplot(DecJan_2018, aes(y = ON ,x = timestamp)) +  -->
<!--     geom_point()+geom_line() -->

<!-- ggplot(DecJan_2018, aes(y = X1W, x = timestamp)) +  -->
<!--     geom_point()+geom_line() -->

<!-- ggplot(DecJan_2018, aes(y = X1M, x = timestamp)) +  -->
<!--     geom_point()+geom_line() -->

<!-- ggplot(DecJan_2018, aes(y = X2M, x = timestamp)) +  -->
<!--     geom_point()+geom_line() -->

<!-- ggplot(DecJan_2018, aes(y = X3M, x = timestamp)) +  -->
<!--     geom_point()+geom_line() -->

<!-- ggplot(DecJan_2018, aes(y = X6M, x = timestamp)) +  -->
<!--     geom_point()+geom_line() -->
<!-- ggplot(DecJan_2018, aes(y = X12M, x = timestamp)) +  -->
<!--     geom_point()+geom_line() -->
<!-- ``` -->


<!-- ```{r} -->
<!-- # Add a scatterplot layer -->
<!-- ggplot(DecJan_2015, aes(y = ON ,x = timestamp)) +  -->
<!--     geom_point()+geom_line() -->

<!-- ggplot(DecJan_2015, aes(y = X1W, x = timestamp)) +  -->
<!--     geom_point()+geom_line() -->


<!-- ``` -->


<!-- ```{r} -->
<!-- # Add a scatterplot layer -->
<!-- ggplot(DecJan_2012, aes(y = ON ,x = timestamp)) +  -->
<!--     geom_point()+geom_line() -->

<!-- ggplot(DecJan_2012, aes(y = X1W, x = timestamp)) +  -->
<!--     geom_point()+geom_line() -->

<!-- ggplot(DecJan_2012, aes(y = X1M, x = timestamp)) +  -->
<!--     geom_point()+geom_line() -->

<!-- ggplot(DecJan_2012, aes(y = X2M, x = timestamp)) +  -->
<!--     geom_point()+geom_line() -->

<!-- ggplot(DecJan_2012, aes(y = X3M, x = timestamp)) +  -->
<!--     geom_point()+geom_line() -->

<!-- ggplot(DecJan_2012, aes(y = X6M, x = timestamp)) +  -->
<!--     geom_point()+geom_line() -->
<!-- ggplot(DecJan_2012, aes(y = X12M, x = timestamp)) +  -->
<!--     geom_point()+geom_line() -->
<!-- ``` -->

<!-- ```{r} -->
<!-- ggplot(DecJan_2017, aes(y = ON, x = timestamp)) +  -->
<!--     geom_point()+geom_line() -->

<!--  ggplot(DecJan_2016, aes(y = ON, x = timestamp)) +  -->
<!--     geom_point()+geom_line() -->

<!--  ggplot(DecJan_2015, aes(y = ON, x = timestamp)) +  -->
<!--     geom_point()+geom_line() -->

<!--  ggplot(DecJan_2014, aes(y = ON, x = timestamp)) +  -->
<!--     geom_point()+geom_line() -->
<!--  ggplot(DecJan_2013, aes(y = ON, x = timestamp)) +  -->
<!--     geom_point()+geom_line() -->


<!--  ggplot(DecJan_2012, aes(y = ON, x = timestamp)) +  -->
<!--     geom_point()+geom_line() -->
<!-- ``` -->