USAGE: This is for US Treasury Yield Rates

Just modify lines 6-12. Run code blocks from top to bottom. Then run last code blocks.

```{r}
PATH = "/Users/anthonynguyen/Desktop/IMA_bootcamp/Week_4/TREASURY_RATES/"
FILENAME = "USTREASURY_YIELD.csv"
holiday_var = "USIndependenceDay"
days_before_holiday <- 15
days_after_holiday <- 15
# Switch: 1 (4 weeks), 2 (8 weeks)
case <- 2
```


```{r}
# Load Libraries
library(lubridate)
library(dplyr)
library(ggplot2)
library(plotly)
library(timeDate)

# Concatenate PATH and FILENAME strings
File_Path = paste(PATH,FILENAME,sep="")

# READ in CSV and name it "DATA"
DATA <- read.csv(File_Path)

##############################################################################
# Create a new table named "rates_to_track" from "LIBOR" with column name "time stamp" containing entries with format Year-Month-Day 
##############################################################################
rates_to_track <- DATA

#rates_to_track %>% rename(timestamp = Date)
# Convert date format to year-month-day
#rates_to_track <- rates_to_track  %>% mutate(timestamp = as.Date(dmy(rates_to_track$Date)))  
##############################################################################

##############################################################################

# listHolidays() will give you a list of possible holidays to use
# In this case, we're using ChristmasDay

holidays <- c(holiday_var)  
Year_begin = 2003
Year_end = 2019

#https://stackoverflow.com/questions/41825688/loop-over-holidays-in-timedate-package

# Create a Table named "holiday_dates" line 59-63
  
# Holiday        | Date 
# ChristmasDay     2003-12-25
# ChristmasDay     2004-12-25
# ............     ..........
# ChristmasDay     2009-12-25 

holiday_dates = do.call(rbind,
        lapply(holidays, function(i){
          foo <- match.fun(i)  
          data.frame(Holiday = i,
                     Date = as.Date(foo(Year_begin:Year_end)))
        }))
#############################################################################

# A function that finds how far a date is from the given holiday (the minimum distance). returns a column of this distance and the year of the holiday

close_to_holiday <- function(input_date){
  distance_from_all_holidays <- mutate(holiday_dates, relative_date = floor(as.period(interval(Date, input_date) ) %/% days(1) ) )%>%
    mutate(absolute_relative_date = abs(relative_date)) %>% arrange(absolute_relative_date)
  return(c(distance_from_all_holidays[1, "relative_date"], year(distance_from_all_holidays[1, "Date"])))
}

#############################################################################
```

```{r message=FALSE}

# next two functions are a hack to make the dataframe wrangling work, can be made better 
get_relative_date <- function(input_date){
  return(close_to_holiday(input_date)[1])
}

get_relative_holiday_year <- function(input_date){
  return(close_to_holiday(input_date)[2])
}

#############################################################################

# Finally, add relative holiday data to the dataframe and filter for the days you need 

rates_to_track_with_holiday_data <- rates_to_track %>% mutate(relative_date = lapply(Date, get_relative_date) ) %>% mutate(holiday_year = lapply(Date, get_relative_holiday_year)) %>%
  filter(relative_date >= days_before_holiday * -1 & relative_date <= days_after_holiday)

# Filter NA data
if(case == 2){rates_to_track_with_holiday_data <- na.omit(rates_to_track_with_holiday_data)}

```

```{r}
# Creates vector Years_array = ("2004", "2005",...,"2018")
Years_array <- paste(c(min(as.double(rates_to_track_with_holiday_data$holiday_year)):max(as.double(rates_to_track_with_holiday_data$holiday_year))))
Number_of_Years <- length(Years_array)

# Create Heaviside function for data wrangling
Heaviside <- function(x,a = 0){if(x==0){return(0)} else{return((sign(x)+1)/2)}}

# Function performs regression on a given year in "holiday_data"
linear_regression <- function(year,holiday_data,case){
  
  holiday_data <- holiday_data %>% filter(as.double(holiday_year) == as.double(year))
  return(lm(switch(case,X1.MO,X2.MO) ~ as.integer(relative_date),data = holiday_data))}
  # change relative_date to week.day

# Function filter data in "holiday_data" in a given year
filtered_data <- function(year,holiday_data){
  holiday_data <- holiday_data %>% filter(as.double(holiday_year) == as.double(year))
  return(holiday_data)}

# Vector of intercepts beta_0's
vector_intercept = c()
for(j in c(1:Number_of_Years)){
  vector_intercept[j] = coef(linear_regression(Years_array[j],rates_to_track_with_holiday_data,case))[1]
}

# Vector of tabular data from year 2004-2019
vector_data_table = c()
for(j in c(1:Number_of_Years)){
  vector_data_table[[j]] <- filtered_data(Years_array[j],rates_to_track_with_holiday_data)
}

# Add columns which includes recentered rates and Pre column
for(j in c(1:Number_of_Years)){
  vector_data_table[[j]] <- vector_data_table[[j]] %>% mutate(recentered_rates = switch(case,X1.MO,X2.MO) - vector_intercept[j]) %>% mutate(Pre = lapply(vector_data_table[[j]]$relative_date,Heaviside))
}

# Concatenate my tabular data from each year
largeData <- vector_data_table[[1]]

if(case == 1){for(j in c(2:Number_of_Years)){
  largeData <- rbind(largeData,vector_data_table[[j]])
}} else{largeData <- vector_data_table[[1]]}


# Construct linear regrerssion model 
# recentered_rates (response), relative_date (predictor), Pre (binary categorical predictor)

model_recentered <- lm(recentered_rates ~ as.integer(Pre), data = largeData)
summary(model_recentered)

model_recentered_pre <- lm(recentered_rates ~ as.integer(relative_date) + as.integer(Pre), data = largeData)
summary(model_recentered_pre)

model_recentered_pre_interaction <- lm(recentered_rates ~ as.integer(relative_date) + as.integer(Pre) + as.integer(relative_date) * as.integer(Pre) , data = largeData)
summary(model_recentered_pre_interaction)

# Scatter Plot of recentered_rates vs relative_date
ggplot(largeData) + geom_point(aes(x = as.numeric(relative_date), y = recentered_rates, color = holiday_year))

```

```{r}
summary(model_recentered)
#r_squared_adj_model_1 <- summary(model_recentered)$adj.r.squared
#r_pvalue_model_1 <- summary(model_recentered)$coefficients[2,4]
```
# ```{r}
# plot(model_recentered$residuals)
# abline(h=0)
# shapiro.test(model_recentered$residuals) ##null hypothesis: normal
# qqnorm(model_recentered$residuals)
# qqline(model_recentered$residuals)
# car::qqPlot(model_recentered$residuals) ##normality assumptions not satisfied
# ``` 
```{r}
summary(model_recentered_pre)
#r_squared_adj_model_2 <- summary(model_recentered_pre)$adj.r.squared
#r_pvalue_model_2 <- summary(model_recentered)$coefficients[2,4]
```

```{r}
summary(model_recentered_pre_interaction)
```